name: Deploy Laravel + Vite App to FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install NPM dependencies
        run: npm install

      - name: Build frontend (Vite)
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir deploy

          for dir in app bootstrap config database public resources routes storage; do
            if [ -d "$dir" ]; then
              cp -R "$dir" deploy/
            fi
          done

          cp artisan deploy/
          cp composer.* package.json deploy/ 2>/dev/null || true

          # Ako postoji build u dist/, kopiraj ga u public/
          if [ -d dist ]; then
            mkdir -p deploy/public/dist
            cp -R dist/* deploy/public/dist/
          fi

          echo "⚠️ .env fajl ide ručno na server!"

      - name: Create ZIP for FTP upload
        run: |
          cd deploy
          zip -r ../deploy.zip .
          cd ..

      - name: Upload ZIP to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: public_html/
